name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  checks: write
  contents: write
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --frozen-lockfile
      - name: solidity unit tests
        run: forge test -v
